name: Build and deploy Next.js (normal SSR) to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install and build dependencies (frontend)
        working-directory: apps/frontend
        run: |
          npm install
          npm run build
      
      - name: Zip build output
        working-directory: apps/frontend
        run: |
          zip -r frontend.zip .next node_modules package.json package-lock.json

      - name: Login to Azure (Service Principal)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8DC825D65050499A8CE13D2F7E7BA4E8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E6879F36F9D04481B37DA7154FA19B77 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4FAA18EB0E1947A6A972154E759188FE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'campomaq-pim'      # e.g. campomaq-pim
          slot-name: 'Production'
          package: apps/frontend/frontend.zip
